---
name: Build and publish a Docker image to ghcr.io
on:

  # publish on releases, e.g. v2.1.13 (image tagged as "2.1.13" - "v" prefix is removed)
  release:
    types: [published]

  # publish on pushes to the main branch (image tagged as "latest")
  push:
    branches: [main]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
#
jobs:
  docker_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - uses: actions/checkout@v2

      #
      - name: Login to ghcr
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      #
      - uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install ORAS using Nix
        run: nix-env -iA nixpkgs.oras

      #
      - name: Report free disk space
        run: df -h

      #
      - name: Build docker image
        run: |
          nix build .#dockerImage

      #
      - name: Report free disk space
        run: df -h

      #
      - name: Push Docker image directly using ORAS
        run: |
          oras push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest \
            --artifact-type application/vnd.docker.container.image.v1+json \
            ./result.tar

      #
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
